import { ZeppelinPluginDocs } from "../../types.js";
import { zGiveawaysConfig } from "./types.js";

export const giveawaysPluginDocs: ZeppelinPluginDocs = {
  prettyName: "Giveaways",
  configSchema: zGiveawaysConfig,
  type: "stable",
  description:
    "Run giveaways with a persistent \"Enter\" button (survives bot restarts) and optional entry requirements — required/bypass/blacklisted roles, a message count (`-messages <period>:<count>` or `<period>:<min>-<max>`), an activity points count (`-activity <count>` or `<min>-<max>`, checked against whatever counter `activity_counter_name` in this plugin's config points to — default `activity`), and an Economy coin balance (`-coins <count>` or `<min>-<max>`, read from whatever counter Economy is actually configured to use). Every one of these is a plain minimum unless you give it a `min-max` range (e.g. `-activity 100-1000` only admits members with 100 to 1000 activity points). Start one with `-giveaway start <duration> <prize> -winners <n> -channel #channel` (e.g. `-giveaway start 1d Nitro -winners 2`), end one early with `-giveaway end <id>`, cancel with `-giveaway cancel <id>`, and see active/recent giveaways with `-giveaway list`. Reroll winners with `-giveaway reroll <message id> [-amount n]` (default 1), where `<message id>` is the giveaway's own announcement message. Set `manager_roles` in this plugin's config to the role ID(s) allowed to manage giveaways — that's the entire permission model here, used both for these commands and for who can see the dashboard's Giveaways page. Configure reusable `templates` (channel, embed color, bypass/blacklisted roles, extra entries per role, claim time) and apply one with `-template <name>` when starting a giveaway, or name one `default` to have it apply automatically. Set `-claim <duration>` (or a template's `claim_time`) to require winners to click \"Claim Prize\" within that window or be automatically rerolled. Winners also get \"Create Thread\" (a private thread with just that winner, the host, and the holder if the prize is staff-held — each winner gets their own, they're never shared; manager-role holders can also see it via their role's Manage Threads permission) and \"Participants\" (an ephemeral list of who's entered and how many entries they have) buttons. Mark a giveaway as staff-held with `-holder <user>` when starting it (or the dashboard's \"Prize is staff-held\" toggle) if a staff member is physically holding the prize rather than handing it out directly — that person is added to each winner's thread alongside the host so they can coordinate the handoff.",
};
