name: Deploy Zeppelin

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '# build')
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          debug: true
          script: |
            echo "connected successfully"
            set -e
            cd Zeppelin/Zeppelin
            git pull
            docker compose -f docker-compose.lightweight.yml down
            docker compose -f docker-compose.lightweight.yml build
            docker compose -f docker-compose.lightweight.yml up -d